# Configuración para H2 (Base de datos en memoria, no requiere instalar nada)
spring.datasource.url=jdbc:h2:mem:calidad_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para que veas tus tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Para que cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto de la aplicación
server.port=9090
spring.sql.init.mode=always